# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cc/eecs151/sp20/class/eecs151-abm/Downloads/fpga_labs_sp20-master/lab5/constrs/pynq-z1.xdc

# Block Designs: bd/z1top_fifo_display_bd/z1top_fifo_display_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z1top_fifo_display_bd || ORIG_REF_NAME==z1top_fifo_display_bd} -quiet] -quiet

# IP: bd/z1top_fifo_display_bd/ip/z1top_fifo_display_bd_rgb2dvi_0_0/z1top_fifo_display_bd_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z1top_fifo_display_bd_rgb2dvi_0_0 || ORIG_REF_NAME==z1top_fifo_display_bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/z1top_fifo_display_bd/ip/z1top_fifo_display_bd_z1top_fifo_display_0_0/z1top_fifo_display_bd_z1top_fifo_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z1top_fifo_display_bd_z1top_fifo_display_0_0 || ORIG_REF_NAME==z1top_fifo_display_bd_z1top_fifo_display_0_0} -quiet] -quiet

# XDC: bd/z1top_fifo_display_bd/z1top_fifo_display_bd_ooc.xdc
